   <!-- Main script -->
   <script src="{{asset('frontend/scripts/main.js')}}"></script>
   <script src="{{asset('frontend/scripts/quantum-aldar.js')}}"></script>
   <script src="https://www.google.com/recaptcha/api.js" async defer></script>
   
   <script src="https://assets.juicer.io/embed.js" type="text/javascript"></script>


    <!-- Facebook Pixel Code -->

   <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
   <script type="application/ld+json">
       {
           "@context" : "http://schema.org",
           "@type" : "LocalBusiness",
           "name" : "Provis",
           "image" : "https://www.provis.ae/images/logo.png",
           "telephone" : "600-505056",
           "email" : "info@provis.ae",
           "address" : {
"@type" : "PostalAddress",
"streetAddress" : "Yas Mall, Yas Island",
"addressLocality" : "Abu Dhabi",
"addressCountry" : "UAE",
"postalCode" : "130520"
           }
       }
   </script>
   <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
   <script>
       !function (f, b, e, v, n, t, s) {
           if (f.fbq) return; n = f.fbq = function () {
n.callMethod ?
   n.callMethod.apply(n, arguments) : n.queue.push(arguments)
           };
           if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
           n.queue = []; t = b.createElement(e); t.async = !0;
           t.src = v; s = b.getElementsByTagName(e)[0];
           s.parentNode.insertBefore(t, s)
       }(window, document, 'script',
           'https://connect.facebook.net/en_US/fbevents.js');
       fbq('init', '711566605911691');
       fbq('track', 'PageView');
   </script>
   <noscript>
       <img height="1" width="1" src="https://www.facebook.com/tr?id=711566605911691&ev=PageView&noscript=1" />
   </noscript>
   <!-- End Facebook Pixel Code -->



   <!-- LikedIn Pixel -->
   <script type="text/javascript">
       _linkedin_partner_id = "499699";
       window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
       window._linkedin_data_partner_ids.push(_linkedin_partner_id);
   </script>
   <script type="text/javascript">
       (function () {
           var s = document.getElementsByTagName("script")[0];
           var b = document.createElement("script");
           b.type = "text/javascript"; b.async = true;
           b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
           s.parentNode.insertBefore(b, s);
       })();
   </script>
   <noscript>
       <img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=499699&fmt=gif" />
   </noscript>
   <!-- End LikedIn Pixel -->



   <!-- Google Tag Manager -->
   <script>
   (function (w, d, s, l, i) {
       w[l] = w[l] || []; w[l].push({
           'gtm.start':
new Date().getTime(), event: 'gtm.js'
       }); var f = d.getElementsByTagName(s)[0],
           j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
       })(window, document, 'script', 'dataLayer', 'GTM-KJ9RB8S');</script>
   <!-- End Google Tag Manager -->



   <!-- Global site tag (gtag.js) - Google Ads: 762788491 -->
   <script async src="https://www.googletagmanager.com/gtag/js?id=AW-762788491"></script>
   <script>
       window.dataLayer = window.dataLayer || [];
       function gtag() {
           dataLayer.push(arguments);
       } gtag('js', new Date());
       gtag('config', 'AW-762788491');
       //below for google analytics
       gtag('config', 'UA-134272116-1');
       //below for floodlight tag
       gtag('config', 'DC-9200188');
   </script>
       <!--
       Event snippet for Provis_Landing Pages on Provis Landing Pages: Please do not remove.
       Place this snippet on pages with events you’re tracking.
       Creation date: 02/16/2019
       -->
       <script>
           gtag('event', 'conversion', {
'allow_custom_scripts': true,
'send_to': 'DC-9200188/landi0/provi0+standard'
           });
       </script>
       <noscript>
           <img src="https://ad.doubleclick.net/ddm/activity/src=9200188;type=landi0;cat=provi0;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;ord=1?" width="1" height="1" alt="" />
       </noscript>
       <!-- End of event snippet: Please do not remove -->

   
   <link href="https://assets.juicer.io/embed.css" media="all" rel="stylesheet" type="text/css" />

   



   <script type="text/javascript">
       window._genesys = {
         widgets: {
             main: {
               theme: "light",
               preload: [ "webchat", "sidebar", "common" ]
           },
           webchat: {
             transport: {
               type: 'purecloud-v2-sockets',
               dataURL: 'https://api.mypurecloud.de',     // replace with API URL matching your region
               deploymentKey : '78c6ce9d-3de5-41f1-80a5-b785eb47cd31',  // replace with your Deployment ID
               orgGuid : '774efaa0-b8b4-4c80-8e63-3b56e06a8c6d',              // replace with your Organization ID
               interactionData: {
                 routing: {
                   targetType: 'QUEUE',
                   targetAddress: 'Default Queue',
                   priority: 2
                 }
               }
             },
             userData: {
                 webUrl: window.location.href
             }
           },
           sidebar: {
               showOnStartup: true,
               position: 'right',
               expandOnHover: true,
               channels: [
                   {
                       name: 'Webchat', 
                       clickOptions: {}, 
                       displayName: 'Web Chat', 
                       displayTitle: 'Web Chat', 
                       icon: 'chat', 
                       onClick: function ($, CXBus, Common) {
                            CXBus.command( "WebChat.open", getAdvancedConfig() );
                       } 
                   }
               ]
           }
         }
       };

       function getAdvancedConfig() {
           return {
             formJSON: {
                   wrapper: "<table></table>",
                   inputs: [
                       {  
           id: 'cx_webchat_form_firstname',
           name: 'firstName',
           maxlength: '100',
           placeholder: 'Required',
           label: 'First Name',
           "validate": function(event, form, input, label, $, CXBus, Common){
               return validateTextField(event, form, input, label, $, CXBus, Common);
           }
                       },
                       {  
           id: 'cx_webchat_form_lastname',
           name: 'lastName',
           maxlength: '100',
           placeholder: 'Required',
           label: 'Last Name',
           "validate": function(event, form, input, label, $, CXBus, Common){
               return validateTextField(event, form, input, label, $, CXBus, Common);
           }
                       },
                       {  
           id: 'cx_webchat_form_email',
           name: 'email',
           maxlength: '100',
           placeholder: 'Required',
           label: 'Email',
           "validate": function(event, form, input, label, $, CXBus, Common){
               return validateTextField(event, form, input, label, $, CXBus, Common);
           }
                       },
                       {  
           id: 'cx_webchat_form_phone',
           name: 'phone',
           maxlength: '100',
           placeholder: 'Required',
           label: 'Phone',
           "validate": function(event, form, input, label, $, CXBus, Common){
               return validateTextField(event, form, input, label, $, CXBus, Common);
           }
                       },
                       {  
           id: 'cx_webchat_form_topic',
           name: 'topic',
           maxlength: '100',
           placeholder: 'Required',
           label: 'Topic',
           type: "select",
                           options: [
                               {
                                   "text": "General Enquiry",
                                   "value": "General Enquiry"
                               },
                               {
                                   "text": "Leasing",
                                   "value": "Leasing"
                               },
                               {
                                   "text": "Consultancy Services",
                                   "value": "Consultancy Services",
                               },
                               {
                                   "text": "Property Management",
                                   "value": "Property Management",
                               },
                               {
                                   "text": "Owners' Association",
                                   "value": "Owners' Association",
                               },
                               {
                                   "text": "Clubhouse and Lifestyle",
                                   "value": "Clubhouse and Lifestyle",
                               }
                           ]
                       }
                   ]
              }
           };
       }

       function validateTextField(event, form, input, label, $, CXBus, Common){
           if(event.type != "blur" && event.type != "keyup"){	
               if(input != undefined){
                   if(input[0].value === '' || input[0].value === undefined){
       return false;
                   }
               }
           }
           return true;
       }
   </script>
   <script  src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
   <script src="https://apps.mypurecloud.de/widgets/9.0/cxbus.min.js" onload="javascript:CXBus.configure({debug:false,pluginsPath:'https://apps.mypurecloud.de/widgets/9.0/plugins/'}); CXBus.loadPlugin('widgets-core');"></script>
   <script type="text/javascript">
       $(document).ready(function() {
           $('#chat').click( function() {
               CXBus.command("WebChat.open", getAdvancedConfig());
           });
       });
       
       //Predictive 
       
       (function (a, t, c, l, o, u, d) {
           a['_genesysJourneySdk'] = o;
           (a[o] =
               a[o] ||
               function () {
                   (a[o].q = a[o].q || []).push(arguments);
               }),
               (a[o].l = 1 * new Date());
           (u = t.createElement(c)), (d = t.getElementsByTagName(c)[0]);
           u.async = 1;
           u.src = l;
           u.charset = 'utf-8';
           d.parentNode.insertBefore(u, d);
       })(window, document, 'script', 'https://apps.mypurecloud.de/journey/sdk/js/web/v1/ac.js', 'ac');
       ac('init', '774efaa0-b8b4-4c80-8e63-3b56e06a8c6d', { region: 'euc1' });
       ac('pageview');

       ac('forms:track', 'form', {
           captureFormDataOnAbandon: true,
       });

       ac(
           'load',
           'autotrackScrollDepth',
           {
               scrollDepthEvents: [{ percentage: 100, eventName: 'scroll_depth_100' }],
           },
           function () {
               console.log('"autotrackScrollDepth" has been loaded');
           }
       );

       setTimeout(function () {
           ac('record', 'timeout-30');
       }, 30000);

       let oPlugin = CXBus.registerPlugin('Plugin');
       oPlugin.before('WebChat.open', function (oData) {
           try {
               if (oData.proactive) {
                   oData.form = getAdvancedConfig().form;
                   oData.formJSON = getAdvancedConfig().formJSON;

                   return oData;
               }

               return oData;
           } catch (error) {
               return oData;
           }
       });
       
       
   </script>
<script>
!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="YQC88-CUP5U-JZ5CV-94EPH-VKYAL",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"YQC88-CUP5U-JZ5CV-94EPH-VKYAL",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+'dy onload="document._l();">'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="nyt2jwycci6zyy7pmxfa-f-955e46f0a-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"34","ak.cp":"1065735","ak.ai":parseInt("631806",10),"ak.ol":"0","ak.cr":214,"ak.ipv":4,"ak.proto":"h2","ak.rid":"2279848f","ak.r":46096,"ak.a2":e,"ak.m":"dscb","ak.n":"essl","ak.bpcip":"110.39.164.0","ak.cport":62247,"ak.gh":"2.18.60.28","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1676633546","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==aCTW5uZwcvjHSM13b0TUOsRbAO2xXWQM678EdpkLCT169EGPlzgblEm6i5kjFCXNenmBNrS+j/BQ2RbrnV29X5M67nmxrFSgVEsUzW4SirNM/FnnbPAt4uyd698eFTNVH1v2aCNHWtXoZxh/HeSRbcfeRyZasdb6jdzG7RuhP7bJYBOWjT+2Li+OEaKhgH+iJFWgQyxk6c+fLTl60wD58UUs7V8Fnrua0niAGikLgQ85F5UKHsTLpZAojmFsVDUHfdvVQS3kWJ06GY2Ookra0+FjV4QKjNfR8xELXH2SdR7ywjCBRXKn+HgaU46faCycFh+SW5kqOaIGd6Knx99Uq6ASOXFe0+8ed5Brdpy5Yb+TbqZ0KF6n8Mwgj2H6PjcZPz7pRjxY5hElkeP0X4zoRQszzWtBkN8hfyr9Dl7IU0c=","ak.pv":"33","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script>